### PR TITLE
Create a dictionary of tech words

### LINKED ISSUE #104: Add more technology words
Hello I'd like to formally add a whole bunch of technology words such as "JSON", "NoSQL", "Steganography", "RDBMS" in addition to function words like "VARCHAR" , "SUBSTR". I'd also like to append "https" to react.txt as it is the more secure version of the protocol. 

I'd like to start by adding a file called sql.txt to the dictionaries folder featuring words dealing with databases and their functions. And add some more common programming related terms to the main dictionary.txt.

### PR DESCRIPTION
**Pull request by a2937**
As part of submitting a pull request, please:

[ ] Attempt to add tests for your change. If you're having difficulty, feel free to open the PR and ask for help.
[X] Add a line to the Unreleased section of CHANGELOG.md describing your change (and crediting yourself if you'd like!)

I attempted to add as many technology related words that I could find. If there are any issues or typos or words that shouldn't be there be sure to let me know and I will remove extra words. 

Also officially on the record; there is an assertion failure when running the builtin tests. However upon closer inspection; it appears to be a part of default behavior. 

Closes #104

### CODE REVIEW

**Review by tbroadley — COMMENTED** [review]
Thank you for this!

And thanks for pointing out the assertion failure in the tests. Is the error `WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree`? I think that's acceptable for now. I may need to upgrade `@typescript-eslint/typescript-estree` to fix that.

Could you please add a reference to the new dictionary in this section of the README? https://github.com/tbroadley/spellchecker-cli#built-in-dictionaries

**Comment by a2937** [comment]
Thank you. Those extra words were added completely by accident.

**Comment by a2937** [comment]
Mainly because I didn't use two dictionaries at once when making my initial list to sort through.

**Comment by a2937** [comment]
It's not a warning. It's a fail. 

Assertion error of retext-repeated-words

**Comment by tbroadley** [comment]
Ah yes, I've seen that test failure too. Can't quite recall why it happens off the top of my head. https://github.com/tbroadley/spellchecker-cli/issues/106

**Comment by a2937** [comment]
My best guess judging by the following lines of code:

https://github.com/tbroadley/spellchecker-cli/blob/f79e66bbc8e6797c93489d5c209ea825285f06aa/test/cli-test.ts#L344-L351

is that previously this code checked for a standard output message because that's what the plugin used to do. But now it throws an actual error.

**Pull request merged**
