### PR TITLE
Add support for TOML to the frontmatter plugin

### PR DESCRIPTION
**Pull request by bryanfriedman**
I ran into a case where we were using both TOML and YAML for frontmatter and it turned out the spellchecker was assuming YAML and not ignoring TOML frontmatter. I believe this additional code will allow for either TOML or YAML frontmatter to be ignored or parsed correctly when keys are specified.

### CODE REVIEW

**Comment by bryanfriedman** [comment]
That file was already there and I didn’t see a test for it but I think the frontmatter tests get covered okay by the frontmatter-incorrect*md files.

Yes, I can add a section to the readme and changelog but I wasn’t sure what section to put it in. Do the changes go under [unreleased] in the changelog or do I create a new version section?

**Comment by tbroadley** [comment]
> That file was a toml version of the frontmatter.md file that was already there and I didn’t see a test that one either. I think the frontmatter tests get covered okay by the frontmatter-incorrect*md files so I can delete those other two if we don’t need them.

Understood - it makes sense to me to delete those two files. I might add them back later and add tests for them. Good catch!

> And yes, I can add a section to the readme and changelog but I wasn’t sure what section to put it in. Do the changes go under [unreleased] in the changelog or do I create a new version section?

Yes, they go under [unreleased] - sorry for the confusion.

**Comment by bryanfriedman** [comment]
Perfect. I’ll get that all updated today. Thanks!

**Comment by bryanfriedman** [comment]
@tbroadley Hope this is good to go now. Thanks for the help!

**Comment by tbroadley** [comment]
Ah as it turns out one of the tests _did_ use `frontmatter.md`. It expected there to be two fixtures for each plugin (including `frontmatter`): one with no errors and one containing some errors. I've added the file back.

**Comment by tbroadley** [comment]
Thanks for the contribution! I just release v4.3.0, which contains this change.

**Pull request merged**
