### PR TITLE
Remove error limit

### LINKED ISSUE #28: Too many misspelling error even if all misspell patterns are mentioned in `--ignore`
```
api/data/series/query.md
  206:8-206:13  warning  Too many misspellings; no further spell suggestions are given  overflow      retext-spell
```

Probably this behavior is caused by default `max` setting set to 30 in `retext-spell`, and `--ignore` feature takes place after `retext-spell` plugin finishes its work.

### PR DESCRIPTION
**Pull request by raipc**
Resolves #28

### CODE REVIEW

**Comment by raipc** [comment]
OK, I will try

**Comment by tbroadley** [comment]
Thank you! One other thing: would you mind writing an entry in the changelog?

**Comment by raipc** [comment]
Done

**Comment by raipc** [comment]
Thank you!

**Pull request merged**
